# -*- coding: utf-8 -*-
"""calculo do Ki.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1946jExeOhH-ZASCpaarAzW5EOBHw-0LZ

# Exercício 1 de variáveis, inputs e operações aritméticas

Faça um programa que calcula o Ki, que é a constante de inibição no contexto de um ensaio de inibição enzimática. Em seguida, o programa deve imprimir o Ki na tela.

Inputs do usuário
"""

ic50 = float(input('Digite o valor de ic50: '))

S = float(input('Concentração do substrato: '))

Km = float(input('Constante de Michaelis: '))

"""Fórmula"""

Ki = (ic50/(1 + (S/Km)))

Ki

"""Imprimindo o valor de Ki na tela"""

print('O valor da constante de inibição é',round(Ki,3))

from rdkit import Chem