# -*- coding: utf-8 -*-
"""Captura de insetos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vK_atIk6UAzlB6SP5WYMHYXrxX3N9kFb
"""



"""#Exercício 3 de variaveis, inputs do usuário e operadores aritméticos

Crie um programa que:

a) Pergunte ao usuário quantos espécimes de insetos ele coletou em campo

b) Pergunte ao usuário quantos dias durou a coleta

c) Imprima na tela a média de espécimes foram coletados por dia

Inputs do usuário
"""

especimes = int(input('Quantos espécimes foram coletados? '))

especimes

dias_de_coleta = int(input('Quantos dias de campo dutou a coleta? '))

dias_de_coleta

especimes_por_dia = especimes/dias_de_coleta

especimes_por_dia

"""Imprimindo informaçõa na tela"""

print('A média de espécimes coletados por dia foi de',round(especimes_por_dia,2))