# -*- coding: utf-8 -*-
"""Coleta de espécies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wstRq_ukE3v8ZB9h9sh-SUjp7TmVfew8
"""



"""#Exercício 2 de coleções

Faça um programa que pergunte ao usuário quantas espécies ele coletou. Em seguida, o programa deverá perguntar o nome de cada espécie e quantidade coletada, e armazenar as informações em um dicionário. Posteriormente, ele deve calcular a soma de todos os indivíduos coletados e a média de ind. coletados por espécie. 
Por último, deve imprimir na tela as informações sobre cada espécie nesse formato:

*Espécie: xxx, espécimes coletados: xxx*

Deve imprimir também a soma e a média de coletas por espécie.

Entrada do usuário com a quantidade de espécies coletadas
"""

quant_esp_coletadas = int(input('Quantas espécies foram coletadas? '))

"""Gerando um dicionário com as espécies e espécimes coletados"""

coletas = dict()

for i in range(0,quant_esp_coletadas):
  especie = str(input('Nome da espécie: '))
  especimes = int(input('Espécimes coletados: '))
  coletas[especie] = especimes

"""Obtendo a soma e a média de coletas"""

soma = 0
for i in coletas.values():
  soma = soma + i

media = soma/quant_esp_coletadas

"""Imprimindo as informações"""

for especies,especimes in coletas.items():
  print(f'Espécie: {especies},espécimes coletados: {especimes}')

print(f'Média de espécimes coletados: {media}. Soma total: {soma}')