# -*- coding: utf-8 -*-
"""Crescimento bacteriano.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11CU3_q0vu4XjjKJjaUIdNbwc4hak2TBO

#Exercício 2 de loops de repetições

Uma bactéria possui população inicial de 500 indivíduos. Sabe-se que, a cada intervalo de 3 horas, a população de bactérias aumenta em cerca de 2,5 vezes. Faça um script que preveja em quantas horas a população de bactérias chegará a 100.000 indivíduos

Variáveis iniciadoras
"""

popinit = 500

treshoras = 0

"""Loop while """

while popinit < 100000:
  popinit = popinit*2.5
  treshoras = treshoras + 1
  print(popinit)

"""Imprimindo na tela a quantidade de horas"""

horas = treshoras*3

print(f'A população levará cerca de {horas} horas para atingir 100.000 indivíduos')