# -*- coding: utf-8 -*-
"""Identificação de famílias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2RdhYIPIGyQOTHzee6YaCpndqqr8mB5

#Exercício 1 de condicionais

O usuário deve digitar o nome de uma família biológica. Se o nome da família terminar com -aceae, o programa deve informar que se trata de uma família de plantas; se terminar com -idae, se trata de uma família de animais; se não tiver nenhum sufixo, o programa deve afirmar que se trata de um táxon desconhecido

Entrada do usuário
"""

nome_familia = str(input('Digite o nome da família: '))

"""Condicionais"""

if nome_familia[-4:] == 'idae':
  print('Se trata de uma família de animal')
elif nome_familia[-5:] == 'aceae':
  print('Se trata de uma família de plantas')
else:
  print('Não foi posível identificar a família taxonômica')