# -*- coding: utf-8 -*-
"""Manipulação de strings - parte 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rHWq4T3-qmCpFOm7d9de_FOF1_-B2_Q0

#Manipulação de strings - parte 2
"""

frase = '''Eu gosto muito de 
Python 
É a melhor linguagem que já conheci'''

print(frase)

'caa' in 'casa'

palavra = 'paralelpipedo'

palavra[-3]

print(f'''Especimes coletados\tespécies coletadas
56\t\t\t12
44\t\t\t10
61\t\t\t8''')