# -*- coding: utf-8 -*-
"""Massa de sequência peptídica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14MItvwGjEyWCpLIsAq3zWjehrAbOvSGm

#Exercício 1 do capítulo de coleções

O usuário deve digitar uma sequência de aminoácidos. O programa deverá validar se essa sequência é válida (se a string contém letras de aminoácidos) e depois deve retornar a massa dessa sequência de acordo com a massa de cada aa em um dicionário

Variável iniciadora
"""

massa_seq = 0

"""Loop que percorre cada aminoácido e verifica se o aminoácido é válido"""

while True:
  seqAA = str(input('Digite a sequência de aminoácidos: ')).upper()
  invalida = False
  for aa in seqAA:
    if aa not in 'ARNDCEQHILKMFPSTWYV':
      invalida = True
  if invalida == True:
    print('Sequência inválida')
  else:
    break

"""Dicionário com o símbolo de cada aa e sua respectiva massa"""

massa_aa = {'A':71.08,
                'R':156.19,
                'N':114.11,
                'D':115.09,
                'C':103.15,
                'E':129.12,
                'Q':128.13,
                'G':57.05,
                'H':137.14,
                'I':113.16,
                'L':113.16,
                'K':128.18,
                'M':131.20,
                'F':147.18,
                'P':97.12,
                'S':87.08,
                'T':101.11,
                'W':186.22,
                'Y':163.18,
                'V':99.13}

"""Loop que percorre cada aminoácido e adiciona sua massa ao peptídeo que inicia vazio"""

for aa in seqAA:
  massa_seq = massa_seq + massa_aa[aa]

"""Imprimindo mensagem na tela"""

print(f'A massa correspondente da sequência digitada é',round(massa_seq,2),'g/mol')