# -*- coding: utf-8 -*-
"""Matrizes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Icf-eofvdjncE6hcKDQL5FoqVdc8DA2L

# Matrizes
"""

import numpy as np

matriz = np.array([[2, 3, 1],
                   [4, 5, 7]])

matriz

matriz.shape #formato de linha e colunha

matriz[0] #consulta por posição

matriz[0][1] #consulta de coluna e linha

matriz[1][2] #percorrer linha e coluna

for i in range(matriz.shape[0]): #percorrer toda a matriz
  print(matriz[i])
  for j in range(matriz.shape[1]): #percorre a linha e o conteúdo
    print(matriz[i][j])

"""Exercícios"""

