# -*- coding: utf-8 -*-
"""Nome_de_especies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16us-mUirLwlFXqywJRxlWT6rah7aBES4

#Exercício 1 do capítulo de Strings

O usuário deve digitar um nome científico de uma espécie.
O programa deve deixar a inicial do nome em maiúscula. Em seguida,
o programa deverá abreviar o nome científico, deixando apenas a inicial do gênero e o epíteto específico

Entrada do usuário
"""

nome_especie = str(input('Digite o nome da espécie: '))

"""Tornando a inicial do nome maiúscula"""

capitalize = nome_especie.capitalize()

capitalize

"""Abreviando o nome científico digitado"""

#Homo sapiens
#H. sapiens
começo = capitalize.find(capitalize[1])
fim = capitalize.find(' ')
substituida = capitalize[começo:fim]

substituida

abreviada = capitalize.replace(substituida,'.')

print('Nome abreviado: ',abreviada)