# -*- coding: utf-8 -*-
"""Operadores condicionais ORIGINAL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/124Y2dx-w0CndmkwRkYMkacj0V9kFQYlb

# Operadores condicionais
"""

if 5 > 3:
  print('5 é maior que 3')

if 5 > 6:
  print('5 é maior')
else:
  print('5 não é maior')

if 5 > 5:
    print('5 é maior')
elif 5 < 5:
    print('5 é menor')
else:
    print('São iguais')

n = 3
if n == 4:
  print('n é igual a 4')
else:
  if n == 3:
    print('n igual a 3')
  else:
    print('n não é igual a 4 nem 3')

x = 2
y = 3

if (x > 1) and (y % 2 == 0):
  print('x é maior que 1 e 2 é par')
else:
  print('Uma ou nenhuma das condições acima foram satisfeitas')