# -*- coding: utf-8 -*-
"""transcricao de sequencia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12dId6YmC3i62Kzqv-GmAzSLX4Yqdv7M5

#Exercício 1 de estruturas de repetição


Escreva um programa que tome uma sequência de DNA como input do usuário e retorne uma sequência de RNA transcrita

Input do usuário
"""

seqDNA = str(input('Digite sua sequência de DNA: ')).upper()

seqDNA

"""loop de repetição"""

seqRNA = ''
for nucleotideo in seqDNA:
  if nucleotideo == 'A':
    seqRNA = seqRNA + 'U'
  elif nucleotideo == 'T':
    seqRNA = seqRNA + 'A'
  elif nucleotideo == 'C':
    seqRNA = seqRNA + 'G'
  elif nucleotideo == 'G':
    seqRNA = seqRNA + 'C'

seqRNA

"""Retornando a sequência de RNA"""

print(f'A sequência de RNA correspondente é {seqRNA}')