# -*- coding: utf-8 -*-
"""Transcricao com dicionarios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1575x1AHikvJa_n7FlUf-aReyaIxcIuSJ

#Exercício 3 de coleções

O usuário deve digitar uma sequência de DNA, e o programa deve transcrever essa sequência para uma sequência de RNA
"""



"""Input do usuário"""

seqDNA = str(input('Digite a sequência de DNA: ')).upper()

"""Sequência de RNA vazia"""

seqRNA = ''

"""Dicionário"""

dna_to_rna = {'A':'U','C':'G','G':'C','T':'A'}

"""Loop de repetição"""

for nucleotideo in seqDNA:
  seqRNA = seqRNA + dna_to_rna[nucleotideo]

"""Imprimindo a sequência de RNA na tela"""

print(f'A sequência de RNA correspondente é {seqRNA}')